Move to Stack for build system and support 7.10

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,20 +1,52 @@
 sudo: false
-language: haskell
+language: c
+
+cache:
+  directories:
+    - $HOME/.gcc-arm-embedded
+    - $HOME/.stack
+
+matrix:
+  include:
+    - env: GHCVER=7.8.4 STACK_YAML=stack.yaml
+      addons: {apt: {packages: [ghc-7.8.4,gcc-multilib,libev-dev], sources: [hvr-ghc]}}
+    - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml
+      addons: {apt: {packages: [ghc-7.10.3,gcc-multilib,libev-dev], sources: [hvr-ghc]}}
+    - env: GHCVER=8.0.1 STACK_YAML=stack-8.0.yaml
+      addons: {apt: {packages: [ghc-8.0.1,gcc-multilib,libev-dev], sources: [hvr-ghc]}}
+
+  allow_failures:
+    - env: GHCVER=8.0.1 STACK_YAML=stack-8.0.yaml
+
 before_install:
-- git clone https://github.com/galoisinc/ivory
-- export IVORY_REPO=$PWD/ivory
-- git clone https://github.com/galoisinc/tower
-- export TOWER_REPO=$PWD/tower
+  # Download and unpack the stack executable
+  - mkdir -p ~/.local/bin
+  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
+  - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
+  # Set up the ARM GCC toolchain
+  - if [ ! -d $HOME/.gcc-arm-embedded/*/bin ];
+    then
+      mkdir -p $HOME/.gcc-arm-embedded;
+      wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 -O- | tar xjf - -C $HOME/.gcc-arm-embedded;
+    fi
+  - echo $HOME/.gcc-arm-embedded/*/bin
+  - ls $HOME/.gcc-arm-embedded/*/bin
+  - export PATH="$(echo $HOME/.gcc-arm-embedded/*/bin):$PATH"
+  - ghc --version
+  - stack --version
+  - arm-none-eabi-gcc --version
+
 install:
-- cabal install cabal-install
-- cabal install alex-3.1.4 happy
+  # Check out depenendency repos, then check out the branch that
+  # matches the current branch name in this repo. If one doesn't
+  # exist, don't fail, in case we're branched in this repo but just
+  # depending on master elsewhere.
+  #
+  # Travis seems to have no problem with the multi-line if above,
+  # but barfs when we format this one nicely.
+  - for repo in ivory tower; do git clone https://github.com/galoisinc/$repo; (cd $repo; git checkout $TRAVIS_BRANCH) || true; export ${repo^^}_REPO=$PWD/$repo; done
+  # tweak the relative paths in stack.yaml
+  - sed -i "s;\.\./;$PWD/;g" $STACK_YAML
+
 script:
-- make create-sandbox
-- make
-- make test
-ghc:
-- 7.8
-notifications:
-  slack:
-    secure: meAyckfvj2cJQyyOHFCwb0dtK+eNIhBPWVICp8L23vbQDs2ps1uo+GGZu0rTwG1skS9y4/tma95ZM3n3PJeLKWl03FVAH17YxNNbTpaIy4YVzqqdksrXfnjvKkmuyAp23PMAEPis6UoKse/oe5V5kWV2DeduhgaZ/9AtGG7UpcM=
-    secure: c5bGu7JC3Q0OeDx3mOA8fU8T/5AKj0R1FhLFAsrDp4sqoWc5NxJ1asdc6vPN/KZ8e5ncczg8xJlyN9ksGzO/sJlhqvXYlvg9A8ExeDqFteu6Zx5YwRNuKqeIlmCfauZwP5agH23vFZWuUd6govQUu+J7lXciSTOFPC7Vi/diqwo=
+  - make travis-test
